services:
  ecommerce:
    restart: always
    build:
      dockerfile: Dockerfile  # default docker look into this
      context: .
    ports:
      - 8000:8000
    volumes:
      - ecommerce:/ecommerce
    image: ecommerce:1.0
    container_name: ecommerce
    command: >
      sh -c "python3 manage.py migrate &&
      gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - ecommerce:/ecommerce
    ports:
      - 80:80
    depends_on:
      - ecommerce
      - db

  db:
    image: postgres:16.1-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data

#  redis:
#    image: redis:alpine
#
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A app worker -l info
#    volumes:
#      - ./app:/app
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db
#      - redis
#      - app

volumes:
  postgres:
  ecommerce: