# Generated by Django 4.2.6 on 2023-10-26 12:14

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Buyer'), (2, 'Seller')], default=1),
        ),
    ]
